#!/usr/bin/env rake
#Rake.application.options.trace = true
require 'fileutils'

def name
  @name ||= Dir.pwd[/[^\/]+$/]
end

desc "Build project with ocra"
task 'build' do
  system "ocra --icon icon.ico src/#{name}.rb --no-lzma --chdir-first --no-autoload --innosetup #{name}.iss"
end

desc "Copy installer to dropbox folder"
task 'dropbox' do
  Dir.glob('Output/*').map{|x| x[/[^\/]*$/]}.each do |file|
    raise 'no dropbox folder!' unless ENV['DROPBOX']
    folder = [ENV['DROPBOX'], name].join('/').squeeze('/')
    FileUtils.mkdir(folder) unless File.exists?(folder)
    FileUtils.cp "Output/#{file}", folder
    url = [ENV['DROPBOX_public_url'], name, file].join('/')
    puts "uploaded to #{url}"
  end
end

task 'git' do
  server = ARGV[1] || 'foo'
  puts <<EOF
git commands:
-------------
cd my_repo
git init
git remote add origin ssh://#{server}/repos/#{name}
git add .
git commit -m "Initial commit"
git push -u origin master
EOF
end