# you can put any configurable options in here
# login information for example
email: foo@gmail.com
password: 12345

# example database section
#database:
#  adapter: mysql
#  database: template
#  username: root
#  password: 12345
#  host: localhost
#  encoding: 'utf8'

# example proxies section
#proxies:
#- www.host1.com:80
#- localhost:8080
#- 127.0.0.1:8888
